import { type AiProvidersConfig } from 'src/engine/metadata-modules/ai/ai-models/types/ai-providers-config.type';

// Kept out of ai-providers.json so the catalog-sync projection test stays
// green. That file is generated from models.dev; OpenRouter is a gateway
// this fork always wants, keyed by OPENROUTER_API_KEY.
export const OPENROUTER_BUILTIN_PROVIDERS: AiProvidersConfig = {
  openrouter: {
    npm: '@ai-sdk/openai-compatible',
    name: 'openrouter',
    label: 'OpenRouter',
    apiKey: '{{OPENROUTER_API_KEY}}',
    baseUrl: 'https://openrouter.ai/api/v1',
    models: [
      {
        name: 'openai/gpt-5.6-luna',
        label: 'GPT-5.6 Luna (OpenRouter)',
        modelFamily: 'GPT',
        inputCostPerMillionTokens: 0.2,
        outputCostPerMillionTokens: 1.2,
        cachedInputCostPerMillionTokens: 0.02,
        cacheCreationCostPerMillionTokens: 0.25,
        contextWindowTokens: 1050000,
        maxOutputTokens: 128000,
        modalities: ['image', 'pdf'],
        supportsReasoning: true,
        efforts: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        name: 'anthropic/claude-sonnet-4.5',
        label: 'Claude Sonnet 4.5 (OpenRouter)',
        modelFamily: 'CLAUDE',
        inputCostPerMillionTokens: 3,
        outputCostPerMillionTokens: 15,
        cachedInputCostPerMillionTokens: 0.3,
        cacheCreationCostPerMillionTokens: 3.75,
        contextWindowTokens: 1000000,
        maxOutputTokens: 64000,
        modalities: ['image', 'pdf'],
        supportsReasoning: true,
      },
      {
        name: 'anthropic/claude-opus-5',
        label: 'Claude Opus 5 (OpenRouter)',
        modelFamily: 'CLAUDE',
        inputCostPerMillionTokens: 5,
        outputCostPerMillionTokens: 25,
        cachedInputCostPerMillionTokens: 0.5,
        cacheCreationCostPerMillionTokens: 6.25,
        contextWindowTokens: 1000000,
        maxOutputTokens: 128000,
        modalities: ['image', 'pdf'],
        supportsReasoning: true,
        efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        name: 'openai/gpt-4o-mini',
        label: 'GPT-4o mini (OpenRouter)',
        modelFamily: 'GPT',
        inputCostPerMillionTokens: 0.15,
        outputCostPerMillionTokens: 0.6,
        contextWindowTokens: 128000,
        maxOutputTokens: 16384,
        modalities: ['image'],
      },
      {
        name: 'openai/gpt-4o',
        label: 'GPT-4o (OpenRouter)',
        modelFamily: 'GPT',
        inputCostPerMillionTokens: 2.5,
        outputCostPerMillionTokens: 10,
        contextWindowTokens: 128000,
        maxOutputTokens: 16384,
        modalities: ['image'],
      },
      {
        name: 'openai/gpt-4.1',
        label: 'GPT-4.1 (OpenRouter)',
        modelFamily: 'GPT',
        inputCostPerMillionTokens: 2,
        outputCostPerMillionTokens: 8,
        contextWindowTokens: 1047576,
        maxOutputTokens: 32768,
        modalities: ['image'],
      },
      {
        name: 'anthropic/claude-sonnet-4',
        label: 'Claude Sonnet 4 (OpenRouter)',
        modelFamily: 'CLAUDE',
        inputCostPerMillionTokens: 3,
        outputCostPerMillionTokens: 15,
        contextWindowTokens: 200000,
        maxOutputTokens: 64000,
        modalities: ['image', 'pdf'],
        supportsReasoning: true,
      },
      {
        name: 'google/gemini-2.5-flash',
        label: 'Gemini 2.5 Flash (OpenRouter)',
        modelFamily: 'GEMINI',
        inputCostPerMillionTokens: 0.3,
        outputCostPerMillionTokens: 2.5,
        contextWindowTokens: 1048576,
        maxOutputTokens: 65536,
        modalities: ['image', 'pdf'],
        supportsReasoning: true,
      },
    ],
  },
};
